using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GestionHoraire.Migrations
{
    public partial class AddSecurityAnd2FA : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Ajouter les colonnes à Utilisateurs (IF NOT EXISTS pour éviter les plantages)
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"FailedLoginAttempts\" integer NOT NULL DEFAULT 0;");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"LockoutUntil\" timestamp without time zone;");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"TwoFactorEnabled\" boolean NOT NULL DEFAULT false;");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"TwoFactorProvider\" character varying(32);");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"AuthenticatorSecretKey\" character varying(128);");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" ADD COLUMN IF NOT EXISTS \"AuthenticatorEnabledAt\" timestamp without time zone;");

            // 2. Créer les nouvelles tables (IF NOT EXISTS)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""SecurityLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer,
                    ""Action"" text NOT NULL,
                    ""Details"" text,
                    ""IpAddress"" text,
                    ""CreatedAt"" timestamp without time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BackupCodes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""CodeHash"" bytea NOT NULL,
                    ""CodeSalt"" uuid NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    ""UsedAt"" timestamp without time zone,
                    ""RevokedAt"" timestamp without time zone,
                    CONSTRAINT ""FK_BackupCodes_Utilisateurs_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Utilisateurs"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""EmailOtps"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""Purpose"" text NOT NULL,
                    ""CodeHash"" bytea NOT NULL,
                    ""CodeSalt"" uuid NOT NULL,
                    ""ExpiresAt"" timestamp without time zone NOT NULL,
                    ""UsedAt"" timestamp without time zone,
                    ""Attempts"" integer NOT NULL DEFAULT 0,
                    ""LastSentAt"" timestamp without time zone NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""FK_EmailOtps_Utilisateurs_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Utilisateurs"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TrustedDevices"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""DeviceName"" text,
                    ""TokenHash"" bytea NOT NULL,
                    ""TokenSalt"" uuid NOT NULL,
                    ""ExpiresAt"" timestamp without time zone NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""FK_TrustedDevices_Utilisateurs_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Utilisateurs"" (""Id"") ON DELETE CASCADE
                );
            ");

            // 3. Création des Index (IF NOT EXISTS n'existe pas directement pour CREATE INDEX en PG < 9.5, mais ici on est sur Neon donc PG 14/15/16)
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_BackupCodes_UserId\" ON \"BackupCodes\" (\"UserId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_EmailOtps_UserId\" ON \"EmailOtps\" (\"UserId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TrustedDevices_UserId\" ON \"TrustedDevices\" (\"UserId\");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "BackupCodes");
            migrationBuilder.DropTable(name: "EmailOtps");
            migrationBuilder.DropTable(name: "SecurityLogs");
            migrationBuilder.DropTable(name: "TrustedDevices");

            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"FailedLoginAttempts\";");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"LockoutUntil\";");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"TwoFactorEnabled\";");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"TwoFactorProvider\";");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"AuthenticatorSecretKey\";");
            migrationBuilder.Sql("ALTER TABLE \"Utilisateurs\" DROP COLUMN IF EXISTS \"AuthenticatorEnabledAt\";");
        }
    }
}
